- name: test
  hosts: all
  connection: local
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
  tasks:


   - name: test
     shell: ansible-galaxy collection install community.kubernetes
     register: test
     
     
   - name: Ensure the myapp Namespace exists.
     community.kubernetes.k8s:
       api_version: v1
       kind: Namespace
       name: myapp_4
       state: present
     register: k8
             

   - debug:
       var: test
      
   - debug:
       var: k8
