- name: test
  hosts: all
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
  tasks:

   - name: test
     shell: |
             git clone https://github.com/miekuskamil/k8s.git
             pwd
             ls -la
             git diff --name-only HEAD
     register: output
     
   - debug:
       var: output
